name: condaenv
channels:
  - conda-forge
  - pytorch
dependencies:
  - cudatoolkit=11.3.1
  - cudnn=8.2.1.32
  - cython=0.29.32
  - faiss-gpu=1.7.2
  - fastai::fastai=2.7.9
  - ffmpeg-python=0.2.0
  - h5py=3.7.0
  - keras=2.10.0
  - lightning-flash[video,image]=0.8.0
  - loguru=0.6.0
  - matplotlib=3.6.1
  - networkx=2.8.7
  - numba=0.56.3
  - numpy=1.23.4
  - opencv=4.5.5
  - oss2=2.16.0
  - pandas=1.5.1
  - pillow=8.4.0
  - pip=22.3
  - pytest=7.2.0
  - python=3.9.13
  - python-magic=0.4.27
  - pytorch::pytorch=1.12.1
  - pytorch::torchvision=0.13.1
  - pytorch::torchaudio=0.12.1
  - scikit-image=0.19.3
  - scikit-learn=1.1.2
  - scipy=1.9.3
  - tqdm=4.64.1
  - pip: 
    - augly[image,video]==1.0.0
    - tensorflow-gpu==2.10.0
    - tslearn==0.5.2