name: Build and publish image

on:
  push:
    branches: [main]
    paths: ['runtime/**', '.github/workflows/build-images.yml']
  pull_request:
    paths: ['runtime/**', '.github/workflows/build-images.yml']

jobs:
  build:
    name: Build, Test, and Publish Image
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        proc: ['cpu', 'gpu']
    env:
      LOGIN_SERVER: metavsc.azurecr.io
      IMAGE: meta-vsc-descriptor-runtime
      SHA_TAG: ${{ matrix.proc }}-${{ github.sha }}
      LATEST_TAG: ${{ matrix.proc }}-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v3
        with:
          repository: facebookresearch/vsc2022
          ssh-key: {{ secrets.SSH_PRIVATE_KEY }}

      - name: Build Image
        run: |
          docker buildx build \
            --build-arg CPU_OR_GPU=${{ matrix.proc }} \
            --tag $LOGIN_SERVER/$IMAGE:$SHA_TAG \
            --tag $LOGIN_SERVER/$IMAGE:$LATEST_TAG \
            -f runtime/Dockerfile .

      - name: Check image size
        run: |
          docker image list $LOGIN_SERVER/$IMAGE

      - name: Tests packages in container
        run: |
          docker run $LOGIN_SERVER/$IMAGE:$SHA_TAG /bin/bash \
            -c "conda run --no-capture-output -n condaenv pytest tests/test_packages.py"

      - name: Log into Azure
        if: github.ref == 'refs/heads/main'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log into ACR with Docker
        if: github.ref == 'refs/heads/main'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push image to ACR
        if: github.ref == 'refs/heads/main'
        run: |
          docker push $LOGIN_SERVER/$IMAGE --all-tags
