name: Build and publish image

on:
  push:
    branches: [main]
    paths: ['runtime/**', '.github/workflows/build-images.yml']
  pull_request:
    paths: ['runtime/**', '.github/workflows/build-images.yml']

jobs:
  build:
    name: Build, Test, and Publish Image
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        proc: ['cpu', 'gpu']
    env:
      LOGIN_SERVER: metavsc.azurecr.io
      IMAGE: meta-vsc-descriptor-runtime
      SHA_TAG: ${{ matrix.proc }}-${{ github.sha }}
      LATEST_TAG: ${{ matrix.proc }}-latest
      GITHUB_ACTIONS_NO_TTY: true

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build Image
        run: |
          docker build \
            --build-arg CPU_OR_GPU=${{ matrix.proc }} \
            --tag $LOGIN_SERVER/$IMAGE:$SHA_TAG \
            --tag $LOGIN_SERVER/$IMAGE:$LATEST_TAG \
            -f ./runtime/Dockerfile .

      - name: Check image size
        run: |
          docker image list $LOGIN_SERVER/$IMAGE

      - name: Tests packages in container
        run: |
          make CPU_OR_GPU=${{ matrix.proc }} \
            LOCAL_IMAGE=$LOGIN_SERVER/$IMAGE:$SHA_TAG \
            test-container

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Prep test assets
        run: cp .github/test_assets/*.csv data/test/

      - name: Test zipping submission_quickstart
        run: |
          make pack-quickstart

      - name: Run submission in container
        run: |
          make CPU_OR_GPU=${{ matrix.proc }} \
            SUBMISSION_IMAGE=$LOGIN_SERVER/$IMAGE:$SHA_TAG \
            test-submission

      - name: Log into Azure
        if: github.ref == 'refs/heads/main'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log into ACR with Docker
        if: github.ref == 'refs/heads/main'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push image to ACR
        if: github.ref == 'refs/heads/main'
        run: |
          docker push $LOGIN_SERVER/$IMAGE --all-tags
